server:
  port: 8080

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password
    connection-timeout: 5s
  datasource:
    url: jdbc:postgresql://localhost:5432/logisticsdb
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: create  # или create-drop для разработки
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  task:
    scheduling:
      enabled: true
      pool:
        size: 5

logging:
  level:
    com.logisticsos: DEBUG